### ISSUE TITLE
Transition when in viewport

### ISSUE THREAD

**Issue by Fewzi** [argyleink/transition.css#15]
It seems that the transitions are working on load, on every divs with transition attribute. I would like to know if it's possible to activate them only when the div is in viewport.

**Comment by argyleink** [comment]
it is 👍🏻 

you'll need to run some javascript to watch elements, and in the event they're in the viewport, set the transition attribute you want on the newly in view element

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
https://github.com/russellgoldenberg/enter-view

**Comment by Fewzi** [comment]
> it is 👍🏻
> 
> you'll need to run some javascript to watch elements, and in the event they're in the viewport, set the transition attribute you want on the newly in view element
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
> https://github.com/russellgoldenberg/enter-view

Thank you ! I'll find the good way with your examples
