### ISSUE TITLE
Bug with CSS code copy on the last 2 effects

### ISSUE THREAD

**Issue by raphaelgoetter** [argyleink/transition.css#27]
Hello and congrats for this tool,

The last 2 transition effects cannot be copy-pasted. Code result is `undefined` :

```
in:custom:circle-swoop
out:custom:circle-swoop
```

**Comment by argyleink** [comment]
nice, i think those just need added here `https://github.com/argyleink/transition.css/blob/svelte/svelte-docsite/src/transitions-map.js` and then it'd have source to copy.

thanks for the report!
